project_chapitre:
    resource: "@ProjectBundle/Controller/ChapitreController.php"
    type:     annotation

project_chapter:
    resource: "@ProjectBundle/Controller/ChapterController.php"
    type:     annotation

project_chapter:
    resource: "@ProjectBundle/Controller/ChapterController.php"
    type:     annotation

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

project:
    resource: "@ProjectBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login:
    path: /login
    defaults:
        _controller: OCUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout