project_place:
    resource: "@ProjectBundle/Controller/PlaceController.php"
    type:     annotation

project_note:
    resource: "@ProjectBundle/Controller/NoteController.php"
    type:     annotation

project_lexicom:
    resource: "@ProjectBundle/Controller/LexicomController.php"
    type:     annotation

project_items:
    resource: "@ProjectBundle/Controller/ItemsController.php"
    type:     annotation

project_events:
    resource: "@ProjectBundle/Controller/EventsController.php"
    type:     annotation

project_heros:
    resource: "@ProjectBundle/Controller/HerosController.php"
    type:     annotation

project_link:
    resource: "@ProjectBundle/Controller/LinkController.php"
    type:     annotation

project_chapitre:
    resource: "@ProjectBundle/Controller/ChapitreController.php"
    type:     annotation

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

project:
    resource: "@ProjectBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login:
    path: /login
    defaults:
        _controller: OCUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout