project_contenu:
    resource: "@ProjectBundle/Controller/ContenuController.php"
    type:     annotation

oc_user_user:
    resource: "@OCUserBundle/Controller/UserController.php"
    type:     annotation

project_project:
    resource: "@ProjectBundle/Controller/ProjectController.php"
    type:     annotation

project_category:
        resource: "@ProjectBundle/Controller/CategoryController.php"
        type:     annotation

project_chapitre:
            resource: "@ProjectBundle/Controller/ChapitreController.php"
            type:     annotation

project_events:
    resource: "@ProjectBundle/Controller/EventsController.php"
    type:     annotation

project_heros:
    resource: "@ProjectBundle/Controller/HerosController.php"
    type:     annotation

project_items:
    resource: "@ProjectBundle/Controller/ItemsController.php"
    type:     annotation

project_lexicom:
    resource: "@ProjectBundle/Controller/LexicomController.php"
    type:     annotation

project_link:
    resource: "@ProjectBundle/Controller/LinkController.php"
    type:     annotation

project_note:
    resource: "@ProjectBundle/Controller/NoteController.php"
    type:     annotation

project_place:
    resource: "@ProjectBundle/Controller/PlaceController.php"
    type:     annotation

project:
    resource: "@ProjectBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile