# app/config/security.yml

security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    OCUserBundle\Entity\User: sha512

  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    #in_memory:
      #memory:
        #users:
          #user:  { password: userpass, roles: [ 'ROLE_USER' ] }
          #admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
    main:
      id: fos_user.user_provider.username
      #entity:
        #class: OCUserBundle\Entity\User
        #property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    #main_login:
      #pattern:   ^/login$
      #anonymous: true
    main:
      pattern:   ^/
      anonymous: true
      provider: main
      form_login:
        login_path: fos_user_security_login
        check_path: fos_user_security_check
        default_target_path: /project
      logout:
        path: fos_user_security_logout
        target: /login
      remember_me:
        secret: %secret%


  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }